# Generated by Django 5.0.6 on 2024-06-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_department_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='hod_profile_pics/'),
        ),
    ]
