# Generated by Django 5.0.6 on 2024-06-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_hod_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hod',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='profile_pic',
        ),
    ]
