# Generated by Django 5.0.6 on 2024-06-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_remove_hod_profile_pic_remove_staff_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='gender',
            field=models.CharField(default='Male', max_length=255),
        ),
        migrations.AlterField(
            model_name='feedbackhod',
            name='feedback_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackstaff',
            name='feedback_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hod',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(default='Male', max_length=255),
        ),
    ]
