# Generated by Django 5.0.6 on 2024-07-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='hod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.hod'),
            preserve_default=False,
        ),
    ]
