# Generated by Django 5.0.6 on 2024-07-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_attendance_clock_in_attendance_clock_out'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceReport',
        ),
    ]
