# Generated by Django 5.0.6 on 2024-07-04 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_delete_attendancereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hr.hod'),
        ),
    ]
